language: node_js
node_js:
  - "6"
env:
  - PG_USER=postgres
install:
  - npm install
  - knex migrate:latest
script: 
  - npm test
services:
  - postgresql
before_script:
  - psql -c 'create database babol;' -U postgres