language: node_js
node_js:
  - "6"
env:
  - PG_USER=postgres
services:
  - postgresql
install:
  - npm install
before_script:
  - psql -c 'create database babol;' -U postgres
  - knex migrate:latest
script: 
  - npm test