version: '2'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    links:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:@db:5432/postgres
      - NODE_ENV=production
  db:
    restart: always
    image: postgres
    environment:
      - PG_HOST=db
      - PGUSER=postgres
      - PGDATABASE=postgres