module.exports = {
  goodSpotifySearchApiResponse: {
    tracks: {
      href: 'https://api.spotify.com/v1/search?query=track%3Amoanin&type=track&offset=1&limit=5',
      items: [
        {
          album: {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/1W8TbFzNS15VwsempfY12H',
                },
                href: 'https://api.spotify.com/v1/artists/1W8TbFzNS15VwsempfY12H',
                id: '1W8TbFzNS15VwsempfY12H',
                name: 'Charles Mingus',
                type: 'artist',
                uri: 'spotify:artist:1W8TbFzNS15VwsempfY12H',
              },
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TR',
              'TW',
              'US',
              'UY',
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/7EOQggjtK8JCqeRz9IG33e',
            },
            href: 'https://api.spotify.com/v1/albums/7EOQggjtK8JCqeRz9IG33e',
            id: '7EOQggjtK8JCqeRz9IG33e',
            images: [
              {
                height: 561,
                url: 'https://i.scdn.co/image/38ff9fb0355ea9ad38b3bc4ea81aab7ea022d9c2',
                width: 640,
              },
              {
                height: 263,
                url: 'https://i.scdn.co/image/3c9c2cb35fb1e24458c34ceb35620dce59a3d08e',
                width: 300,
              },
              {
                height: 56,
                url: 'https://i.scdn.co/image/8d6529f079e713cd7c9a5d683faafa776fefaed2',
                width: 64,
              },
            ],
            name: 'Blues & Roots',
            type: 'album',
            uri: 'spotify:album:7EOQggjtK8JCqeRz9IG33e',
          },
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/1W8TbFzNS15VwsempfY12H',
              },
              href: 'https://api.spotify.com/v1/artists/1W8TbFzNS15VwsempfY12H',
              id: '1W8TbFzNS15VwsempfY12H',
              name: 'Charles Mingus',
              type: 'artist',
              uri: 'spotify:artist:1W8TbFzNS15VwsempfY12H',
            },
          ],
          available_markets: [
            'AD',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'EC',
            'EE',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IS',
            'IT',
            'JP',
            'LI',
            'LT',
            'LU',
            'LV',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'PA',
            'PE',
            'PH',
            'PL',
            'PT',
            'PY',
            'SE',
            'SG',
            'SK',
            'SV',
            'TR',
            'TW',
            'US',
            'UY',
          ],
          disc_number: 1,
          duration_ms: 482959,
          explicit: false,
          external_ids: {
            isrc: 'USAT20001825',
          },
          external_urls: {
            spotify: 'https://open.spotify.com/track/3rFzc8CLVDZ7OOtFa2jPYP',
          },
          href: 'https://api.spotify.com/v1/tracks/3rFzc8CLVDZ7OOtFa2jPYP',
          id: '3rFzc8CLVDZ7OOtFa2jPYP',
          name: 'Moanin\'',
          popularity: 42,
          preview_url: 'https://p.scdn.co/mp3-preview/7b73820ef9d5f6e56dbcfdf50237569f9e1d58b7?cid=null',
          track_number: 3,
          type: 'track',
          uri: 'spotify:track:3rFzc8CLVDZ7OOtFa2jPYP',
        },
        {
          album: {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/6ykfXAed2KOLOMI3R0TZdz',
                },
                href: 'https://api.spotify.com/v1/artists/6ykfXAed2KOLOMI3R0TZdz',
                id: '6ykfXAed2KOLOMI3R0TZdz',
                name: 'Art Blakey & The Jazz Messengers',
                type: 'artist',
                uri: 'spotify:artist:6ykfXAed2KOLOMI3R0TZdz',
              },
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TR',
              'TW',
              'US',
              'UY',
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/5PzlTnVafjgt5RtjTdIKoC',
            },
            href: 'https://api.spotify.com/v1/albums/5PzlTnVafjgt5RtjTdIKoC',
            id: '5PzlTnVafjgt5RtjTdIKoC',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/4cc0114854cb7528bc180fb1c4359e590237cc5d',
                width: 640,
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/1cd14faea6ad52eac3cbf9df1bdc64ce44713a64',
                width: 300,
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/afc0e19ca92a37848af89d9aff217c2ab1bb43d2',
                width: 64,
              },
            ],
            name: 'Moanin\' (The Rudy Van Gelder Edition)',
            type: 'album',
            uri: 'spotify:album:5PzlTnVafjgt5RtjTdIKoC',
          },
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/6QQuESLtKhAOcLW2TeWC2t',
              },
              href: 'https://api.spotify.com/v1/artists/6QQuESLtKhAOcLW2TeWC2t',
              id: '6QQuESLtKhAOcLW2TeWC2t',
              name: 'Art Blakey',
              type: 'artist',
              uri: 'spotify:artist:6QQuESLtKhAOcLW2TeWC2t',
            },
          ],
          available_markets: [
            'AD',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'EC',
            'EE',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IS',
            'IT',
            'JP',
            'LI',
            'LT',
            'LU',
            'LV',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'PA',
            'PE',
            'PH',
            'PL',
            'PT',
            'PY',
            'SE',
            'SG',
            'SK',
            'SV',
            'TR',
            'TW',
            'US',
            'UY',
          ],
          disc_number: 1,
          duration_ms: 570720,
          explicit: false,
          external_ids: {
            isrc: 'USBN29800794',
          },
          external_urls: {
            spotify: 'https://open.spotify.com/track/4Vkk3iD1VrENHJEACNddvt',
          },
          href: 'https://api.spotify.com/v1/tracks/4Vkk3iD1VrENHJEACNddvt',
          id: '4Vkk3iD1VrENHJEACNddvt',
          name: 'Moanin\'',
          popularity: 39,
          preview_url: 'https://p.scdn.co/mp3-preview/e606584d1a87fecd1f7628dbb4ab61897020cd1f?cid=null',
          track_number: 2,
          type: 'track',
          uri: 'spotify:track:4Vkk3iD1VrENHJEACNddvt',
        },
        {
          album: {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/06nevPmNVfWUXyZkccahL8',
                },
                href: 'https://api.spotify.com/v1/artists/06nevPmNVfWUXyZkccahL8',
                id: '06nevPmNVfWUXyZkccahL8',
                name: 'Gregory Porter',
                type: 'artist',
                uri: 'spotify:artist:06nevPmNVfWUXyZkccahL8',
              },
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/3rr6aGHhOVAGikv0EKUgQX',
                },
                href: 'https://api.spotify.com/v1/artists/3rr6aGHhOVAGikv0EKUgQX',
                id: '3rr6aGHhOVAGikv0EKUgQX',
                name: 'Donald Smith',
                type: 'artist',
                uri: 'spotify:artist:3rr6aGHhOVAGikv0EKUgQX',
              },
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/2cK0ZQXA4VPKsFTUxfKBzi',
                },
                href: 'https://api.spotify.com/v1/artists/2cK0ZQXA4VPKsFTUxfKBzi',
                id: '2cK0ZQXA4VPKsFTUxfKBzi',
                name: 'Mansur Scott',
                type: 'artist',
                uri: 'spotify:artist:2cK0ZQXA4VPKsFTUxfKBzi',
              },
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TR',
              'TW',
              'US',
              'UY',
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/0RBVUIOvxc3JeWotCFrHQG',
            },
            href: 'https://api.spotify.com/v1/albums/0RBVUIOvxc3JeWotCFrHQG',
            id: '0RBVUIOvxc3JeWotCFrHQG',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/eb13792d96829f9abce6f9f3be3e8cf9103749e1',
                width: 640,
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/9e6ee273ba078b47226ba54935d24be7672e6a9c',
                width: 300,
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/a6eea6890c80f80e62a24c7b318f1d00e188e724',
                width: 64,
              },
            ],
            name: 'Great Voices of Harlem',
            type: 'album',
            uri: 'spotify:album:0RBVUIOvxc3JeWotCFrHQG',
          },
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/06nevPmNVfWUXyZkccahL8',
              },
              href: 'https://api.spotify.com/v1/artists/06nevPmNVfWUXyZkccahL8',
              id: '06nevPmNVfWUXyZkccahL8',
              name: 'Gregory Porter',
              type: 'artist',
              uri: 'spotify:artist:06nevPmNVfWUXyZkccahL8',
            },
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/2nmVOBlzN7k3jBzy4xm9qY',
              },
              href: 'https://api.spotify.com/v1/artists/2nmVOBlzN7k3jBzy4xm9qY',
              id: '2nmVOBlzN7k3jBzy4xm9qY',
              name: 'Paul Zauner\'s Blue Brass',
              type: 'artist',
              uri: 'spotify:artist:2nmVOBlzN7k3jBzy4xm9qY',
            },
          ],
          available_markets: [
            'AD',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'EC',
            'EE',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IS',
            'IT',
            'JP',
            'LI',
            'LT',
            'LU',
            'LV',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'PA',
            'PE',
            'PH',
            'PL',
            'PT',
            'PY',
            'SE',
            'SG',
            'SK',
            'SV',
            'TR',
            'TW',
            'US',
            'UY',
          ],
          disc_number: 1,
          duration_ms: 419160,
          explicit: false,
          external_ids: {
            isrc: 'ATZ061412101',
          },
          external_urls: {
            spotify: 'https://open.spotify.com/track/6WuVh11dlY080E4zudfFzK',
          },
          href: 'https://api.spotify.com/v1/tracks/6WuVh11dlY080E4zudfFzK',
          id: '6WuVh11dlY080E4zudfFzK',
          name: 'Moanin',
          popularity: 25,
          preview_url: 'https://p.scdn.co/mp3-preview/75faa9a798f28df9400af6d55a6cd2195e580c8f?cid=null',
          track_number: 1,
          type: 'track',
          uri: 'spotify:track:6WuVh11dlY080E4zudfFzK',
        },
        {
          album: {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/118jMO6hdUQeoDOv0XiLIs',
                },
                href: 'https://api.spotify.com/v1/artists/118jMO6hdUQeoDOv0XiLIs',
                id: '118jMO6hdUQeoDOv0XiLIs',
                name: 'Karrin Allyson',
                type: 'artist',
                uri: 'spotify:artist:118jMO6hdUQeoDOv0XiLIs',
              },
            ],
            available_markets: [
              'CA',
              'MX',
              'US',
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/5U3pyucYBx03qlYODcZ6OW',
            },
            href: 'https://api.spotify.com/v1/albums/5U3pyucYBx03qlYODcZ6OW',
            id: '5U3pyucYBx03qlYODcZ6OW',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/1d2eef9a807eb82e31db4b2579deec37071ddbd5',
                width: 640,
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/a45c19d53e3daccec2c89092b3468835d0902f7b',
                width: 300,
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/1137cf069413e6adbe86378f99850b1af747d263',
                width: 64,
              },
            ],
            name: 'By Request: The Best of Karrin Allyson',
            type: 'album',
            uri: 'spotify:album:5U3pyucYBx03qlYODcZ6OW',
          },
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/118jMO6hdUQeoDOv0XiLIs',
              },
              href: 'https://api.spotify.com/v1/artists/118jMO6hdUQeoDOv0XiLIs',
              id: '118jMO6hdUQeoDOv0XiLIs',
              name: 'Karrin Allyson',
              type: 'artist',
              uri: 'spotify:artist:118jMO6hdUQeoDOv0XiLIs',
            },
          ],
          available_markets: [
            'CA',
            'MX',
            'US',
          ],
          disc_number: 1,
          duration_ms: 362560,
          explicit: false,
          external_ids: {
            isrc: 'USC4R0301801',
          },
          external_urls: {
            spotify: 'https://open.spotify.com/track/2ypLxYhcaZObluwvFN8z3v',
          },
          href: 'https://api.spotify.com/v1/tracks/2ypLxYhcaZObluwvFN8z3v',
          id: '2ypLxYhcaZObluwvFN8z3v',
          name: 'Moanin\'',
          popularity: 30,
          preview_url: 'https://p.scdn.co/mp3-preview/c4ef6a3b5338b0f9f79daa3959e37bb08ba11a76?cid=null',
          track_number: 2,
          type: 'track',
          uri: 'spotify:track:2ypLxYhcaZObluwvFN8z3v',
        },
        {
          album: {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify: 'https://open.spotify.com/artist/54YNxT02JdAApvFBhD8ea0',
                },
                href: 'https://api.spotify.com/v1/artists/54YNxT02JdAApvFBhD8ea0',
                id: '54YNxT02JdAApvFBhD8ea0',
                name: 'Mingus Big Band',
                type: 'artist',
                uri: 'spotify:artist:54YNxT02JdAApvFBhD8ea0',
              },
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CA',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MX',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TR',
              'TW',
              'US',
              'UY',
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/37JcsF5m4iDiAzZWMli9Sb',
            },
            href: 'https://api.spotify.com/v1/albums/37JcsF5m4iDiAzZWMli9Sb',
            id: '37JcsF5m4iDiAzZWMli9Sb',
            images: [
              {
                height: 640,
                url: 'https://i.scdn.co/image/91d71c749d945b29097e4225c3037775869c6dee',
                width: 640,
              },
              {
                height: 300,
                url: 'https://i.scdn.co/image/72cee84aeec5add66106c1cca287b9eb0b6ea512',
                width: 300,
              },
              {
                height: 64,
                url: 'https://i.scdn.co/image/cc1e97fd618995e067258fd402442dabfb896665',
                width: 64,
              },
            ],
            name: 'The Essential Mingus Big Band',
            type: 'album',
            uri: 'spotify:album:37JcsF5m4iDiAzZWMli9Sb',
          },
          artists: [
            {
              external_urls: {
                spotify: 'https://open.spotify.com/artist/54YNxT02JdAApvFBhD8ea0',
              },
              href: 'https://api.spotify.com/v1/artists/54YNxT02JdAApvFBhD8ea0',
              id: '54YNxT02JdAApvFBhD8ea0',
              name: 'Mingus Big Band',
              type: 'artist',
              uri: 'spotify:artist:54YNxT02JdAApvFBhD8ea0',
            },
          ],
          available_markets: [
            'AD',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BO',
            'BR',
            'CA',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'EC',
            'EE',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IS',
            'IT',
            'JP',
            'LI',
            'LT',
            'LU',
            'LV',
            'MC',
            'MT',
            'MX',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'PA',
            'PE',
            'PH',
            'PL',
            'PT',
            'PY',
            'SE',
            'SG',
            'SK',
            'SV',
            'TR',
            'TW',
            'US',
            'UY',
          ],
          disc_number: 1,
          duration_ms: 538093,
          explicit: false,
          external_ids: {
            isrc: 'FR14F9300440',
          },
          external_urls: {
            spotify: 'https://open.spotify.com/track/0Mkc4HSM2Ye7PS8TgfW0dn',
          },
          href: 'https://api.spotify.com/v1/tracks/0Mkc4HSM2Ye7PS8TgfW0dn',
          id: '0Mkc4HSM2Ye7PS8TgfW0dn',
          name: 'Moanin\'',
          popularity: 31,
          preview_url: 'https://p.scdn.co/mp3-preview/a097d241ceec970b3b0c9f92ca66060ae1de1f01?cid=null',
          track_number: 5,
          type: 'track',
          uri: 'spotify:track:0Mkc4HSM2Ye7PS8TgfW0dn',
        },
      ],
      limit: 5,
      next: 'https://api.spotify.com/v1/search?query=track%3Amoanin&type=track&offset=6&limit=5',
      offset: 1,
      previous: 'https://api.spotify.com/v1/search?query=track%3Amoanin&type=track&offset=0&limit=5',
      total: 880,
    },
  },
};
